services:
  bot:
    build: .
    container_name: lol_bot
    env_file: 
      - .env
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
      - INTENT_COLLECTION=${INTENT_COLLECTION}
      - PLAYER_COLLECTION=${PLAYER_COLLECTION}
      - TEAM_COLLECTION=${TEAM_COLLECTION}